---

- name: test if chrome cron job already exists
  stat: path=/etc/cron.daily/google-chrome
  register: google_chrome_installed
  tags: google-chrome

- name: download chrome if its repo doesn't already exist
  dnf: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=installed
  when: google_chrome_installed.stat.exists == False
  tags: google-chrome

# Not strictly necessary
- name: install chrome
  dnf: name=google-chrome-stable state=installed
  tags: google-chrome
