---

- name: test if chrome cron job already exists
  stat: path=/etc/cron.daily/google-chrome
  register: google_chrome_installed
  tags: google-chrome

- name: import google RPM signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.google.com/linux/linux_signing_key.pub

- name: download chrome if its repo doesn't already exist
  dnf: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=installed
  when: google_chrome_installed.stat.exists == False
  tags: google-chrome

# Not strictly necessary
- name: install chrome
  dnf: name=google-chrome-stable state=installed
  tags: google-chrome

- name: template chrome cron defaults
  template: src=google-chrome-etc-default.j2 dest=/etc/default/google-chrome owner=root group=root mode=0644
  tags: google-chrome

- name: create chrome incognito shortcut
  copy:
    src: files/google-chrome-incognito.desktop
    dest: /usr/local/share/applications/
    owner: root
    group: root
    mode: 0644