---

- hosts: all
  pre_tasks: 
    - name: include local vars
      tags: always
      ignore_errors: yes
      include_vars: /var/local/ansible-vars.yml

  roles:
    - {role: base, tags: base}
    - {role: google-chrome , tags: google-chrome}
    - {role: firefox, tags: firefox}
    - {role: virthost, tags: virthost}
      #  - {role: pass, tags: pass}
    - {role: sshd, tags: sshd}
    - {role: tailscale, tags: tailscale}
    - {role: tlp , tags: tlp}
      #- powertop 
      #- dropbox
      #- slack
      #- vagrant
  become: yes
