---

- hosts: all
  roles:
    - {role: base, tags: base}
    #- powertop 
    - {role: google-chrome , tags: google-chrome}
      #- dropbox
      #- slack
      #- vagrant
    #- virtualbox
  become: yes
