---

tailscale_baseurl: https://pkgs.tailscale.com/stable/centos/{{ ansible_distribution_major_version }}/$basearch
tailscale_gpgkey: https://pkgs.tailscale.com/stable/centos/{{ ansible_distribution_major_version }}/repo.gpg

