---

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  #tags: vars

- name: import tailscale RPM signing key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ tailscale_gpgkey }}"

- name: configure tailscale repository
  yum_repository: 
    name: tailscale
    description: "https://tailscale.com/kb/1031/install-linux"
    baseurl: "{{ tailscale_baseurl }}"
    gpgcheck: no # This is bad, but consistant with tailscale's repo
    gpgkey: "{{ tailscale_gpgkey }}"
    enabled: yes

- name: install tailscale
  dnf: 
    state: installed
    name: tailscale

- name: enable and start tailscale service
  service: 
    name: tailscaled
    enabled: yes
    state: started
