---

- name: configure slack yum repo
  yum_repository:
    name: slack
    description: slack
    baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64
    enabled: true
    gpgcheck: false # Slack! Y U NO SIGN PACKAGES? 😞
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
  tags: slack

- name: install slack
  dnf: name=slack state=present
  tags: slack
