---

- name: install packages required for virtualbox to compile its kernel modules
  tags: virtualbox
  dnf: name={{ item }} state=installed
  with_items:
    - dkms
    - kernel-devel

- name: enable virtualbox yum repo 
  tags: virtualbox
  template: src=virtualbox.repo.j2 dest=/etc/yum.repos.d/virtualbox.repo owner=root group=root mode=0755

- name: install virtualbox
  tags: virtualbox
  dnf: name=VirtualBox-5.0 state=installed

- name: add my_user to the 'vboxusers' group
  tags: virtualbox
  user:
    name: "{{ my_user }}"
    groups: vboxusers
    append: yes
  when: my_user is defined
