---

- name: install workstation group
  dnf:
    name: "@workstation"
    state: present
    exclude:
      - firefox
      - PackageKit-command-not-found
      - cockpit-ws
      - cockpit
  when: ansible_distribution == "CentOS"

- name: enable epel
  dnf:
    state: present
    name: epel-release
  when: ansible_distribution == "CentOS"
  
- name: disable some services
  service:
    enabled: False
    state: stopped
    name: avahi-daemon
  ignore_errors: yes
  
- name: install base packages
  dnf:
    state: installed
    enablerepo: PowerTools
    name:
            #      - "acpi"
            #- "adobe-source-code-pro-fonts"
      - "alpine"
      - "aspell"
      - "aspell-en"
      - "discount"
      - "elinks"
      - "enscript"
        # - "fzf"
      - "gcc"
      - "gimp"
      - "git"
      - "gnome-tweak-tool"
      - "gvfs-mtp"
      - "iotop"
      - "keepass"
      - "libvirt-client"
      - "libvirt-daemon-config-nwfilter"
      - "ncdu"
      - "nmap"
      - "nmap-ncat"
      - "openssh-clients"
      - "openssl"
      - "perf"
      - "python3-pip"
      - "rsync"
      - "screen"
      - "smartmontools"
      - "sshuttle"
      - "strace"
      - "tcpdump"
      - "vim"
      - "vim-X11"
      - "vim-enhanced"
      - "vim-filesystem"
      - "virt-top"
      - "wavemon"
      - "wireshark"

- name: install fedora-specific packages
  when: ansible_distribution == "Fedora"
  dnf:
    state: present
    name:
      - magic-wormhole
      - httpie
      - "the_silver_searcher"
      - wine
      - fzf

- name: enable rpmfusion-free
  dnf:
    state: present
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-33.noarch.rpm
    disable_gpg_check: true 

- name: enable rpmfusion-nonfree
  dnf:
    state: present
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-33.noarch.rpm
    disable_gpg_check: true 

- name: install ffmpeg (requires rpmfusion)
  dnf:
    state: present
    name: ffmpeg
     
# Stop systemd-resolved from listening to 5355/tcp
- name: configure systemd-resolved
  template: src=resolved.conf.j2 dest=/etc/systemd/resolved.conf 
  notify: restart systemd-resolved

- name: remind self about isolate graphical
  template: src=graphical.issue dest=/etc/issue.d/graphical.issue



