---

- name: Install Virtualization Host package group if on CentOS"
  when: ansible_distribution == "CentOS"
  dnf:
    state: present
    name: "@Virtualization Host"
    exclude:
      - cockpit

- name: Install Virtualization  package group on Fedora"
  when: ansible_distribution == "Fedora"
  dnf:
    state: present
    name: "@Virtualization"
    exclude:
      - cockpit


- name: Install other virt tools
  dnf:
    state: present
    name: 
      - virt-install
      - libguestfs-tools
