---

- name: remove unnecessary packages
  dnf: name={{ item }} state=absent
  with_items:
    - evolution
    - fedora-user-agent-chrome
    - PackageKit-command-not-found

- name: disable some services
  service: name={{ item }} enabled=False state=stopped
  with_items:
    - avahi-daemon

- name: install base packages
  dnf: name={{ item }} state=installed
  with_items:
    - acpi
    - adobe-source-code-pro-fonts
    - alpine
    - aspell
    - aspell-en
    - discount
    - dmenu
    - elinks
    - firefox
    - gcc
    - ghc
    - ghc-xmonad-contrib-devel
    - git
    - gvfs-mtp
    - iotop
    - ipython
    - network-manager-applet
    - nmap-ncat
    - openssh-clients
    - openssl
    - pass
    - perf
    - python3-pip
    - python-pip
    - python-virtualenvwrapper
    - rsync
    - screen
    - smartmontools
    - strace
    - subversion
    - tcpdump
    - thunar
    - vim
    - vim-enhanced
    - vim-filesystem
    - vim-X11
    - virt-top
    - wine
    - wireshark
    - wireshark-gnome
    - xfce4-battery-plugin
    - xfce4-power-manager
    - xfce4-terminal
    - xmobar
    - xmonad
    - xorg-x11-drv-synaptics
    #- xscreensaver-base
