---

- name: remove unnecessary packages
  dnf: name={{ item }} state=absent
  with_items:
    - evolution
    - PackageKit-command-not-found
    - fedora-user-agent-chrome

- name: disable some services
  service: name={{ item }} enabled=False state=stopped
  with_items:
    - avahi-daemon
    - cups

- name: install base packages
  dnf: name={{ item }} state=installed
  with_items:
    - git
    - gcc
    - elinks
    - acpi
    - ipython
    - subversion
    - python-pip
    - python3-pip
    - ghc
    - xmonad
    - xfce4-power-manager
    - xfce4-battery-plugin
    - ghc-xmonad-contrib-devel
    - xmobar
    - dmenu
    - network-manager-applet
    - xorg-x11-drv-synaptics
    - firefox
    - wine
    - thunar
    - gvfs-mtp
    - openssl
    - xfce4-terminal
    - adobe-source-code-pro-fonts
    - rsync
    - openssh-clients
    - pass
    - iotop
    - perf
    - tcpdump
    - nmap-ncat
    - alpine
    #- xscreensaver-base
    - vim
    - vim-filesystem
    - vim-enhanced
    - vim-X11
    - smartmontools
    - discount
    - aspell
    - aspell-en
    - strace
