---

- name: remove unnecessary packages
  dnf: name={{ item }} state=absent
  with_items:
    - evolution
    - PackageKit-command-not-found

- name: disable some services
  service: name={{ item }} enabled=False state=stopped
  with_items:
    - avahi-daemon
    - cups

- name: install base packages
  dnf: name={{ item }} state=installed
  with_items:
    - git
    - gcc
    - elinks
    - acpi
    - ipython
    - subversion
    - python-pip
    - python3-pip
    - ghc
    - xmonad
    - xfce4-power-manager
    - xfce4-battery-plugin
    - ghc-xmonad-contrib-devel
    - xmobar
    - dmenu
    - network-manager-applet
    - xorg-x11-drv-synaptics
    - firefox
    - wine
    - thunar
    - gvfs-mtp
    - openssl
    - xfce4-terminal
    - adobe-source-code-pro-fonts
    - rsync
    - openssh-clients
    - pass
    - iotop
    - perf
    - tcpdump
    - nmap-ncat
    - alpine
    - xscreensaver-base
    - vim
    - vim-filesystem
    - vim-enhanced
    - vim-X11
    - smartmontools


- name: test if chrome repo exists
  stat: path=/etc/yum.repos.d/google-chrome.repo
  register: google_chrome_repo

- name: download chrome if its repo doesn't already exist
  dnf: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=installed
  when: google_chrome_repo.stat.exists == False

# Not strictly necessary
- name: install chrome
  dnf: name=google-chrome-stable state=installed

- name: test if Dropbox repo exists
  stat: path=/etc/yum.repos.d/dropbox.repo
  register: dropbox_repo

- name: download and install Dropbox if its repo doesn't already exist
  dnf: name=https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.02.12-1.fedora.x86_64.rpm state=installed
  when: dropbox_repo.stat.exists == False

- name: install Dropbox
  dnf: name=nautilus-dropbox state=installed

