---

- name: install sshd
  dnf: 
    state: installed
    name: openssh-server

- name: open sshd port
  firewalld:
    port: "{{ sshd_port }}/tcp"
    permanent: yes
    zone: FedoraServer
    state: enabled

- name: Allow sshd to listen on its port
  notify: restart sshd
  seport:
    ports: "{{ sshd_port }}"
    proto: tcp
    setype: ssh_port_t
    state: present

- name: templated sshd config
  notify: restart sshd
  template: 
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
